syntax = "proto3";

package todennus.proto.dto;

option go_package = "github.com/todennus/proto/gen/service/dto";

message FileRegisterUploadRequest {
    int64 user_id = 1;
    int64 max_size = 2;
    repeated string allowed_types = 3;
}

message FileRegisterUploadResponse {
    string upload_token = 1;
}

message FileCreatePresignedURLRequest {
    string file_id = 1;
    int64 ownership_id = 2;
    int64 expiration = 3;
}

message FileCreatePresignedURLResponse {
    string presigned_url = 1;
}

message FileChangeRefcountRequest {
    repeated int64 inc_ownership_id = 1;
    repeated int64 dec_ownership_id = 2;
}

message FileChangeRefcountResponse {}
