syntax = "proto3";

package todennus.proto.dto;

option go_package = "github.com/todennus/proto/gen/service/dto";

import "dto/resource/user.proto";

message UserValidateRequest {
    string username = 1;
    string password = 2;
}

message UserValidateResponse {
    resource.User user = 1;
}

message UserGetByIDRequest {
    int64 id = 1;
}

message UserGetByIDResponse {
    resource.User user = 1;
}

message UserValidateAvatarPolicyTokenRequest {
    string policy_token = 1;
}

message UserValidateAvatarPolicyTokenResponse {
    int64 user_id = 1;
    repeated string allowed_types = 2;
    int32 max_size = 3;
}
